version: "3"

services:
  database:
    image: "mysql:latest"

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mspr-paillote-soleil
      MYSQL_USER: mspr-paillote-soleil
      MYSQL_PASSWORD: dev
    ports:
      - "4306:3306"
    volumes:
      - database_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
  mailcatcher:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]
volumes:
  database_data: